### ISSUE TITLE
pomegranante/add-dependencies should allow specifying the ClassLoader to modify

### ISSUE THREAD

**Issue by tobias** [cemerick/pomegranate#63]
Currently, it uses the single-arity variant of `add-classpath`, which will use the highest modifiable class loader in the the loader hierarchy. There are cases where it is useful to add to a specific class loader for isolation purposes.

**Comment by expez** [comment]
Anything happening on this front?  I'd also find this addition useful.

**Comment by mikub** [comment]
Seems super useful to me. Was exploring doing this with boot but for some reason my impression was that there was no out-of-the-box way how to do it there (pods are completely isolated clojure runtimes whereas i just want to add few classloaders and load different maven poms in each in single clojure runtime). Also even if it was possible in boot I think pomegranate should be a way how to address it, not a build tool (though boot is much more) that requires a buy-in.
I might look into the PR at some stage as well.
P.S. funny thing is I am eating pomegranate while writing this.
