### ISSUE TITLE
File repositories always fail on existence checks

### ISSUE THREAD

**Issue by curtosis** [cemerick/pomegranate#71]
"File" repositories (repositories using a `file:` uri) fail artifact existence checks with "IllegalArgumentException: number of transferred bytes cannot be negative". This is due to an upstream bug in sonatype-aether.

For a discussion and patch, see: https://bugzilla.redhat.com/show_bug.cgi?id=1118341

A workaround is to delete the offending cached artifact(s) from your `~/.m2` repository to force a new "download" rather than existence check.

This would be fixed (presumably) by the move to eclipse-aether in the PR here: https://github.com/cemerick/pomegranate/pull/70

**Comment by cemerick** [comment]
Presumably, hopefully, etc.
