### ISSUE TITLE
Specify local repository

### ISSUE THREAD

**Issue by mikera** [cemerick/pomegranate#75]
Hi,

I'm using CCW (https://github.com/laurentpetit/ccw) which uses pomegranate and I'm having trouble making it use a different local repo from the default (~/.m2).

Is there a way to specify the local repo in order to resolve this issue?

Relevant code in CCW appears to be here:

https://github.com/laurentpetit/ccw/blob/9b323b20a50fe0913cfc9615a2720c1730566a33/ccw.core/src/clj/ccw/leiningen/classpath_container.clj#L131

**Comment by mikera** [comment]
P.S. Not entirely sure if this is a pomegranate or Leiningen or CCW issue...... apologies if I have raised the issue in the wrong place!

**Comment by cemerick** [comment]
It looks like CCW is passing along a leiningen project map (presumably loaded from your `project.clj`), so `:local-repo` seems to be the key you're looking for: https://github.com/technomancy/leiningen/blob/2fb603b/sample.project.clj#L135

**Comment by mikera** [comment]
OK thanks - will try it out!
