### ISSUE TITLE
Please tag 0.3.1 release

### ISSUE THREAD

**Issue by ehashman** [cemerick/pomegranate#82]
Would it be possible for you to tag the 0.3.1 release? GitHub appears to be missing it.

Commit: https://github.com/cemerick/pomegranate/commit/ba0a76f79122f0c7668e8b84b2dc0e74bea1e03b

This would be helpful as I am attempting to upgrade the version of this package uploaded to Debian for facilitating the packaging of Leiningen 2, and the current packaging relies on original tarballs being available.

**Comment by cemerick** [comment]
Done.

**Comment by ehashman** [comment]
Thanks!
