### ISSUE TITLE
Upgrade to a more recent stable Clojure version

### ISSUE THREAD

**Issue by glts** [cemerick/pomegranate#87]
Pomegranate declares a dependency on Clojure 1.3.

According to the Clojure API doc on GitHub, 1.3 is ‘legacy’. The oldest
release that’s still marked ‘stable’ is 1.6. The current version is 1.8.

Would you consider upgrading Clojure to a more recent stable version?
1.6, 1.7, 1.8? (I’m finding it a little difficult to set up a dev
environment for 1.3.) Thank you!

**Comment by cemerick** [comment]
I would prefer to let dependency versions be driven by project needs. I do think the travis config should get a 1.8 test target, but that's a separate issue.

FWIW, you can always mix in a modern clojure via your user profile, so whatever tooling you use is kept happy.
