### ISSUE TITLE
Non-TLS HTTP repositories are unsupported; using a "bare" HTTP repository now requires registering a "wagon" for the insecure transport method (gh-83)

### ISSUE THREAD

**Issue by lgrapenthin** [cemerick/pomegranate#95]
This is a change that after updating Leiningen breaks our entire deployment pipeline.

A warning would have been sufficient to alert incautious users.

What is the intention behind this change? 

It is simply not helpful but in the way. Why do I have to deal with "wagons" now? This tool was supposed to abstract such things away.

**Comment by cemerick** [comment]
Hopefully it's obvious that the changes made were intentional. Perhaps less obvious that Leiningen wasn't the victim of the changes, but their motivator.

Non-HTTPS repositories are bad. You can continue to use them, with some effort, but hopefully you won't.

**Comment by lgrapenthin** [comment]
Well if I upgrade the victim is my budget. This is overcautious security restriction adds zero value in our case. It appears to only patronize people who know and should know what they are doing. A warning would be sufficient, a simple global flag would still be acceptable - breaking things doesn't seem justified here with "HTTP is bad".

**Comment by cemerick** [comment]
I was going to leave a further sarcastic remark regarding the impacts of free software on your budget and just how much I'm worried about "adding value" in your particular case, but I see you're also leaving strident "feedback" in other projects on this topic (i.e. "this is not acceptable" in https://github.com/technomancy/leiningen/issues/2376).

You are very welcome to use the software I and others have collaborated upon here. You are further welcome to bring something constructive to the table. Otherwise, begone.

**Comment by lgrapenthin** [comment]
I didn't attack you personally (for which I have no intention) nor did I swear or do slightest thing that justifies how you treat me here. Acceptance is, as we both know, a subjective measure of a users willingness to adopt a certain change. It is a professional term used all the time in our business. I refuse to be criticized over using it.

I pointed out a potential feature flaw after tracking it down from Leiningen to here, cautiously asking for intentions beyond what I saw and provided the clearest impression of our user experience that I could give. 

Why should I do this anymore if all you do is letting me know that the change is intentional and who motivated it, who is not its victim and that HTTP is bad, and then close the issue?

Probably I should just assume that OSS maintainers only accept criticism of software they made for others if done ceremoniously, in a form that suits their feelings more than the dimension of a problem and that it is perfectly fine if they answer user feedback in any way they please. Especially those which make their users feel stupid. 

Of course I know that the change was intended! I copied its description from the change/commitlog. Did you really not notice that? And aside from your personal criticism I see only confirmation that this is what I guessed. A child safety device, unnecessarily difficult to remove. 

Please think about it and reconsider immediate user feedback as useful contribution in itself. IMO, even without an envelope and flowers, its more useful to everyone than no feedback and should be appreciated. 

I have suggested two acceptable fixes (warning and flag). Which is as constructive as it gets without further direction from you, the maintainer. If you are interested in any of those, or variations thereof, I'm happy to contribute, as I did on many other occasions in the Clojure world. If you have to attack me personally just because I am indicating where your work is not 100% perfect, which is the whole point of this forum, I will be gone very quickly indeed.
